# replicate github-pages production environment for development transparency
lsi: false
safe: true
highlighter: rouge
gist:
  noscript: false
kramdown:
  input: GFM
  hard_wrap: false
  math_engine: mathjax
gems:
  - jekyll-coffeescript
  - jekyll-paginate
